import type { ReportColumn, ReportData, ReportRow } from '../core/report.types';

const escapeHtml = (value: unknown) =>
  String(value ?? '').replace(/[&<>"']/g, (char) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  }[char] || char));

export const generatePdfHtml = <T extends ReportRow>(
  title: string,
  data: ReportData<T>,
  columns: ReportColumn<T>[],
  role: string,
  generatedBy: string,
) => {
  const generatedAt = new Date(data.exportMetadata.generatedAt).toLocaleString();
  const professionalTitle = buildProfessionalTitle(title, data);
  const filterText = Object.entries(data.filtersApplied)
    .filter(([, value]) => value !== undefined && value !== null && value !== '')
    .map(([key, value]) => `${key}: ${value}`)
    .join(' | ') || 'No filters';

  return `<!doctype html>
<html>
<head>
  <title>${escapeHtml(professionalTitle)}</title>
  <style>
    @page { margin: 18mm 14mm 20mm; }
    * { box-sizing: border-box; }
    body { min-height: 100vh; font-family: Inter, Arial, sans-serif; color: #111827; margin: 0; padding-bottom: 48px; display: flex; flex-direction: column; }
    header { border-bottom: 3px solid #4f46e5; padding-bottom: 16px; margin-bottom: 20px; }
    .brand { color: #4f46e5; font-weight: 800; font-size: 20px; }
    h1 { margin: 8px 0 4px; font-size: 24px; }
    .meta { color: #6b7280; font-size: 12px; line-height: 1.6; }
    main { flex: 1; }
    .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 20px 0; }
    .card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; }
    .label { color: #6b7280; font-size: 11px; text-transform: uppercase; }
    .value { font-size: 20px; font-weight: 800; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 12px; }
    th { background: #eef2ff; color: #3730a3; text-align: left; }
    th, td { border-bottom: 1px solid #e5e7eb; padding: 9px; vertical-align: top; }
    footer { position: fixed; right: 0; bottom: 0; left: 0; color: #6b7280; font-size: 11px; border-top: 1px solid #e5e7eb; padding-top: 12px; display: flex; justify-content: space-between; gap: 16px; background: #fff; }
  </style>
</head>
<body>
  <header>
    <div class="brand">Q-over-o</div>
    <h1>${escapeHtml(professionalTitle)}</h1>
    <div class="meta">Generated: ${escapeHtml(generatedAt)}<br>Generated by: ${escapeHtml(generatedBy)} (${escapeHtml(role)})<br>Filters: ${escapeHtml(filterText)}</div>
  </header>
  <main>
  <section class="summary">
    ${data.summary.map((item) => `<div class="card"><div class="label">${escapeHtml(item.label)}</div><div class="value">${escapeHtml(item.value)}</div></div>`).join('')}
  </section>
  <table>
    <thead><tr>${columns.map((column) => `<th>${escapeHtml(column.label)}</th>`).join('')}</tr></thead>
    <tbody>
      ${data.rows.map((row) => `<tr>${columns.map((column) => `<td>${escapeHtml(formatPdfValue(row[column.key], column))}</td>`).join('')}</tr>`).join('')}
    </tbody>
  </table>
  </main>
  <footer><span>Q-over-o Reporting System</span><span>${escapeHtml(professionalTitle)} | Generated ${escapeHtml(generatedAt)}</span></footer>
</body>
</html>`;
};

const titleCaseStatus = (value: unknown) =>
  String(value || '')
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');

const buildProfessionalTitle = <T extends ReportRow>(title: string, data: ReportData<T>) => {
  const paymentStatus = data.filtersApplied.paymentStatus;
  const sessionStatus = data.filtersApplied.status;
  if (title === 'Financial Reports' && paymentStatus === 'completed') return 'Completed Token Purchases';
  if (title === 'Financial Reports' && paymentStatus === 'failed') return 'Failed Token Purchases';
  if (paymentStatus) return `${titleCaseStatus(paymentStatus)} ${title}`;
  if (sessionStatus) return `${titleCaseStatus(sessionStatus)} ${title}`;
  return title;
};

const formatPdfValue = <T extends ReportRow>(value: unknown, column: ReportColumn<T>) => {
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  if (typeof value === 'number') return value.toLocaleString();
  if (typeof value === 'string' && /\d{4}-\d{2}-\d{2}T/.test(value)) return new Date(value).toLocaleString();
  if (typeof value === 'string' && (column.key.toLowerCase().includes('status') || column.label.toLowerCase().includes('status'))) {
    return titleCaseStatus(value);
  }
  return value ?? '';
};
