import type { ReportColumn, ReportRow } from '../core/report.types';

const text = (key: string, label: string, sortable = false, sortKey?: string): ReportColumn<ReportRow> => ({ key, label, sortable, sortKey });

export const reportColumns = {
  tuteeSessions: [
    text('tutor', 'Tutor'),
    text('subject', 'Subject'),
    text('sessionDate', 'Session date', true, 'start_time'),
    text('durationHours', 'Hours', true, 'start_time'),
    text('tokensSpent', 'Tokens', true, 'token_amount'),
    text('reviewSubmitted', 'Reviewed'),
    text('outcome', 'Outcome', false),
    text('status', 'Status'),
  ],
  tuteeWallet: [
    text('reference', 'Reference'),
    text('amountTokens', 'Tokens', true, 'amount_tokens'),
    text('balanceAfter', 'Balance after'),
    text('transactionDate', 'Date', true, 'created_at'),
    text('paymentChannel', 'Channel'),
    text('escrowMovement', 'Escrow'),
    text('type', 'Type'),
    text('status', 'Status'),
  ],
  tutorEarnings: [
    text('reference', 'Reference'),
    text('earningsReleased', 'Released', true, 'amount_tokens'),
    text('pendingEscrow', 'Pending escrow'),
    text('deductions', 'Deductions'),
    text('payoutStatus', 'Payout status'),
    text('qualificationStatus', 'Qualification'),
    text('transactionDate', 'Date', true, 'created_at'),
  ],
  tutorPerformance: [
    text('subject', 'Subject'),
    text('completedHours', 'Hours', true, 'start_time'),
    text('averageRating', 'Rating'),
    text('reviewCount', 'Reviews'),
    text('cancellationRate', 'Cancellation %'),
    text('completionRate', 'Completion %'),
    text('repeatStudentRatio', 'Repeat %'),
    text('qualificationProgress', 'Qualification %'),
    text('sessionDate', 'Date', true, 'start_time'),
  ],
  adminRevenue: [
    text('user', 'User'),
    text('reference', 'Reference'),
    text('amountTokens', 'Tokens', true, 'amount_tokens'),
    text('amountKes', 'KES'),
    text('balanceAfter', 'Balance after'),
    text('type', 'Type'),
    text('status', 'Status'),
    text('transactionDate', 'Date', true, 'created_at'),
  ],
  adminSessions: [
    text('tutor', 'Tutor'),
    text('student', 'Student'),
    text('subject', 'Subject'),
    text('sessionDate', 'Date', true, 'start_time'),
    text('durationHours', 'Hours', true, 'start_time'),
    text('tokens', 'Tokens', true, 'token_amount'),
    text('status', 'Status'),
    text('paymentStatus', 'Payment'),
  ],
  adminUsers: [
    text('user', 'User'),
    text('email', 'Email'),
    text('role', 'Role'),
    text('verified', 'Verified'),
    text('suspended', 'Suspended'),
    text('createdAt', 'Created', true, 'created_at'),
  ],
  adminSubjects: [
    text('subject', 'Subject'),
    text('sessions', 'Sessions'),
    text('hours', 'Hours'),
    text('tokens', 'Tokens'),
    text('cancellations', 'Cancellations'),
    text('cancellationRate', 'Cancellation %'),
  ],
  adminReviews: [
    text('tutor', 'Tutor'),
    text('reviewer', 'Reviewer'),
    text('rating', 'Rating', true, 'rating'),
    text('comment', 'Comment', false),
    text('createdAt', 'Created', true, 'created_at'),
  ],
  adminQualifications: [
    text('tutor', 'Tutor'),
    text('state', 'State'),
    text('qualified', 'Qualified'),
    text('hoursCompleted', 'Hours'),
    text('averageRating', 'Rating'),
    text('uniqueReviewers', 'Reviewers'),
    text('progressPercentage', 'Progress %'),
    text('verified', 'Verified'),
    text('active', 'Active'),
  ],
  exceptions: [
    text('severity', 'Severity'),
    text('category', 'Category'),
    text('message', 'Message', false),
    text('createdAt', 'Created', true, 'created_at'),
  ],
} satisfies Record<string, ReportColumn<ReportRow>[]>;
